### ISSUE TITLE
Custer config not saved

### ISSUE THREAD

**Issue by mnwalker** [bitnami-labs/cabin#80] opened 2018-01-05 05:56 UTC
Been struggling to get cabin to work properly, first issue was self signed certificate on the api which I solved by putting behind cloudflare.

Now I can enter cluster details and connect, but every time I close the app my cluster is gone and I have to enter all config details again.

Android app version 0.4.1 on an S6 edge

**Comment by rickard-von-essen** [comment] 2018-01-05 07:16
Duplicates #76

**Comment by kemcake** [comment] 2018-01-21 06:55
Closing, duplicate of #76 . which is fixed btw

**Closed by kemcake** 2018-01-21 06:55 UTC
